name = "mezzmonteur-analytics"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "mezz_analytics_db"
database_id = "mezz-analytics-db-id"

[triggers]
crons = ["0 3 * * *"]
